### ISSUE TITLE
Addon not working with Omega Beta 2

### ISSUE THREAD

**Issue by sonoseco** [LizardByte/Themerr-kodi#17]
### Describe the Bug

Testing the addon with Omega beta 2, and getting the following errors in the log:
```
2023-12-29 01:41:06.130 T:5530    error <general>: EXCEPTION: Kodi is not playing any file
2023-12-29 01:41:16.379 T:5530     info <general>: Skipped 192 duplicate messages..
2023-12-29 01:41:16.379 T:5530    error <general>: Themerr: [ERROR]: YDL returned an unexpected error while downloading https://www.youtube.com/watch?v=HeOOgQVmi8o: 'xbmcout' object has no attribute 'isatty'
2023-12-29 01:41:16.429 T:5530    error <general>: EXCEPTION: Kodi is not playing any file

```

It's able to determine the movie, but fails to play the song. Any ideas?

**Comment by adamosborne83** [comment]
I can second this issue, logs avaliable if required

**Comment by ReenigneArcher** [comment]
It might be an issue with https://kodi.wiki/view/Add-on:Youtube-dl_Control

It might be an issue with the region of the video.

Can you see that video on YouTube if you open it in your browser? Or is it unavailable?

**Comment by ReenigneArcher** [comment]
Yea, it's probably that add-on.

It's a dependency for Themerr.

I opted to use the Kodi supplied version as I thought it would be cleaner.

I'll create a build later that uses the official source though. Would you mind testing it? If so I'll let you know when it's ready.

**Comment by ReenigneArcher** [comment]
@sonoseco 

I don't know that using youtube-dl as a submodule will fix it, but I have a build here: https://github.com/LizardByte/Themerr-kodi/actions/runs/7358828562?pr=19

> **Note**
> You must be logged in to GitHub to download the artifact. It is also double zipped due to how GitHub uploads artifacts for workflows. The zip within the zip is the one needed for Kodi.

If this doesn't work, there might be something else I can do to fix it... which might be a better solution anyway. For my reference: https://github.com/ytdl-org/youtube-dl/issues/28914

**Comment by ReenigneArcher** [comment]
Weird... it looks like this has already been patched in Kodi's youtube-dl. https://github.com/xbmc/repo-scripts/blob/b1b680b4835d51554006cb4bf9d98b50b5338609/script.module.youtube.dl/lib/YoutubeDLWrapper.py#L19-L27

**Comment by ReenigneArcher** [comment]
This would be the preferred fix. Let me know if #20 works. Artifact is available here: https://github.com/LizardByte/Themerr-kodi/actions/runs/7359114852?pr=20

**Comment by ReenigneArcher** [comment]
> The add-on doesn't seem to respect the timeout settings, I set it to 1 second but it takes 5-6 seconds or more regardless of what is selected as the timeout.

This is due to how long it takes youtube-dl to determine the audio url. I might pre-fetch this in a future release.

> After I let it play for while and later exit out of the movie page, the song keeps playing until the end, I have to either manually go into the player and stop it, or restart Kodi.

Once the item is deselected (for the timeout period), the theme should stop playing. If you select another item with a theme it should start playing. You do not need to be on the movie information page for the theme to play, but it will play in the list view.

I personally wanted it to play only in the movie information page, which is how it works with Plex and Jellyfin, but in Kodi selecting a movie starts playing it, and it's kind of annoying to get to the movie information page (must go through context menu... at least on default skin).

> A setting to set the volume level of the song would be great!

It's a good idea. Probably possible to add.

> The screen briefly flashes and displays the loading icon when the song begins to play, could this be avoided? I'm not sure if this one is even possible due to how Kodi works, it might be more a skin setting maybe?

This one is pretty annoying, I agree. I think it's something specific to each skin, so I'm not sure how to handle that yet. I think [tvtunes](https://github.com/latts9923/service.tvtunes) hacks the existing skin, which I didn't want to do. I would like a way to somehow hide that, and the playing indicator though.

Here are a few of my other ideas for the plugin: https://github.com/LizardByte/Themerr-kodi/pull/1#issuecomment-1868388532
