### ISSUE TITLE
not working with Fen and Artic Fuse

### ISSUE THREAD

**Issue by sasagr** [LizardByte/Themerr-kodi#18]
### Describe the Bug

No theme is played while browsing movie list using Fen addon and Artic Fuse on apple tv device with Kodi Nexus 20.2
Attached log:
https://paste.kodi.tv/ehuzihejod

**Comment by ReenigneArcher** [comment]
According to the dev of Fen, they are adding the correct ids. https://www.reddit.com/r/Addons4Kodi/comments/18td3cj/comment/kfgcov1/?utm_source=share&utm_medium=web2x&context=3

No idea if that's actually the case though without the source code.

I'll re-open this if source code of Fen is provided as a git repo, not zip archive, where I can browse the source code online.

**Comment by ReenigneArcher** [comment]
A couple things.

A. What skin are you using?
B. Can you show logs after enabling debug logging? Themerr doesn't log anything otherwise.
C. Be sure to select a movie that is actually in our database -> https://app.lizardbyte.dev/ThemerrDB

**Comment by ReenigneArcher** [comment]
I ended up adjusting the logic to try to be more flexible with video addons.

Can you test this build? https://github.com/LizardByte/Themerr-kodi/actions/runs/7361949628?pr=22

> **Note**
>
> You must be logged in to GitHub to download the artifact. It is also double zipped due to how GitHub uploads artifacts for workflows. The zip within the zip is the one needed for Kodi.

**Comment by sasagr** [comment]
Unfortunately it is still not working. Here the log.
https://paste.kodi.tv/eninivokun

FYI I tried using the Artic Fuse widget, then I tried selecting the movie from the addon (both Fen and Fen Light) and also from its information page. Outside the attached log, I also tried the same steps using the default kodi skin, but also in this cast it wasn't working.

**Comment by ReenigneArcher** [comment]
Those errors are because of a regional issue... I'm guessing you are in the EU? See https://github.com/ytdl-org/youtube-dl/pull/32638

I personally submitted that PR to fix it in youtube-dl... but it hasn't made it into Kodi's version yet. https://github.com/xbmc/repo-scripts/blob/b1b680b4835d51554006cb4bf9d98b50b5338609/script.module.youtube.dl/lib/youtube_dl/extractor/youtube.py#L255

Even if it is in Kodi's version, this plugin will require additional changes to make it work for you similar to https://github.com/LizardByte/Themerr-plex/pull/203 (and https://github.com/LizardByte/Themerr-plex/pull/215)

Anyway, the fact that it's finding a youtube url at all proves it will work with these video addons, so I will get this merged.

Feel free to open a separate issue for the EU issue.
